apiVersion: v1
kind: Service
metadata:
  name: {{ include "devtoolbox.fullname" . }}
  labels:
    {{- include "devtoolbox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "devtoolbox.selectorLabels" . | nindent 4 }}